modLoader="javafml"
loaderVersion="[47,)" # 1.20.1
license="MIT"

[[mods]]
modId="eraser"
version="1.3.0"
displayName="Eraser Mod"
authors="test"
description='''
A mod that erases entities instantly.
'''

[[dependencies.eraser]]
modId="forge"
mandatory=true
versionRange="[47,)" 
ordering="NONE"
side="BOTH"

[[dependencies.eraser]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]" # 1.20.x?
ordering="NONE"
side="BOTH"

