modLoader="javafml"
loaderVersion="[47,)" # 1.20.1
license="MIT"

[[mods]]
modId="c11eraser"
version="1.4.1"
displayName="Eraser Mod"
authors="test"
description='''
A mod that erases entities instantly.
'''

[[dependencies.eraser]]
modId="forge"
mandatory=true
versionRange="[47,)" # 1.20.x?
ordering="NONE"
side="BOTH"

[[dependencies.eraser]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

